### ISSUE TITLE
Default to `--release` builds?

### ISSUE THREAD

**Issue by fitzgen** [ferrous-systems/cargo-flamegraph#15]
Instead of providing `--release` to turn on release mode, I suggest defaulting to release mode and providing a `--dev` option for development builds.

This would have the downside of not matching `cargo run`, but I am confident that release modes are the correct default here: I can count on one hand the number of times I've ever wanted to profile a dev build.

**Comment by spacejam** [comment]
This is something I'm a bit conflicted about because of the significantly worse debug info that is often emitted. An approach that @matklad brought up would be to detect whether debug symbols are enabled at compiletime, and if not, issue a warning to the user. I think that may hit both sides, because `--release` profiles are certainly the better target to base engineering decisions on, as so many things that show up in debug profiles are optimized away anyway.

**Comment by spacejam** [comment]
@matklad just made this the default behavior! I'll cut version 0.1.7 now that includes these changes
